name: hello

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to test the result action to azure queue
    steps:
    - name: Send job status with metadata to AzureQueue
      id: send-job-status-to-azure-queue
      uses: amongil/gh-action-push-workflow-last-job-status-to-azure-queue@v0.1.0
      with:
        STORAGE_ACCOUNT_NAME: alvarostorageaccount1234
        STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_ACTION_STORAGE_ACCOUNT_KEY}}
        QUEUE_NAME: alvaroqueue
        JOB_STATUS: ${{ job.status }}
    - name: Get the data sent from last step
      run: echo "The data sent was ${{ steps.send-job-status-to-azure-queue.outputs.data-sent }}"
