name: hello

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: amongil/gh-action-push-result-to-azure-queue@v7
      with:
        who-to-greet: ${{ job.status }}
    - name: Get the data sent
      run: echo "The time was ${{ steps.hello.outputs.data-sent }}"
